# -*- coding: utf-8 -*-
"""speechtotextSchabu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GMFJ7ScYrEuqOb1NEPp9FEyJwRirQQRo
"""

# Azure Cognitive Services Speech API
# !pip install azure-cognitiveservices-speech
import azure.cognitiveservices.speech as speechsdk
import time
import os
import sys
from pydub import AudioSegment

def speech_recognize_continuous_from_file(key, reg, file):
    """performs continuous speech recognition with input from an audio file"""
    speech_config = speechsdk.SpeechConfig(subscription=key, region=reg)
    audio_config = speechsdk.audio.AudioConfig(filename=file)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)
    done = False
 
    def stop_cb(evt):
        # """callback that stops continuous recognition upon receiving an event `evt`"""
        # print('CLOSING on {}'.format(evt))
        speech_recognizer.stop_continuous_recognition()
        nonlocal done
        done = True

    text_output = []
    def save_text_output(evt):
        text_output.append(evt.result.text)

    speech_recognizer.recognized.connect(save_text_output)
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)
 
    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
    return text_output

# Store all speech to text Input Here


src = sys.argv[2]+"/mp3/"+sys.argv[1] #"C:/Users/Pranav Patel/Documents/schabu/back_end/routes/public/mp3/"+sys.argv[1]
dst = sys.argv[2]+"/wav/"+sys.argv[1] # "C:/Users/Pranav Patel/Documents/schabu/back_end/routes/public/wav/"+sys.argv[1]+".wav"

sound = AudioSegment.from_mp3(src)
sound.export(dst, format="wav")

if os.path.exists(dst):
    text_output = speech_recognize_continuous_from_file("b58d19e457574aa39bc0f8b9b763cd55", "australiaeast", dst)
    print(text_output[0])
